apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
spec:
  replicas: 1
  selector:
    matchLabels:
      run: api-service
  template:
    metadata:
      labels:
        run: api-service
    spec:
      containers:
        - name: api-service
          image: registry.gitlab.com/a.samanta/demodocker:latest
      imagePullSecrets:
        - name: api-service-deployment-tokengitlab