apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: api-service
    app.kubernetes.io/instance: api-service-instance
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: kubectl
  name: api-service
spec:
  selector:
    run: api-service
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 3000
